use_frameworks!

source 'https://cdn.cocoapods.org/'
source 'https://github.com/Kalanhall/Specs.git'

platform :ios, '9.0'

target 'KLKeyboard_Example' do
  pod 'KLKeyboard', :path => '../'

  target 'KLKeyboard_Tests' do
    inherit! :search_paths

    
  end
end
